// Throwaway structural comparison: A overview to detail; B inline accordions.
// All records are fictional; changes live only in this module's memory.
const $ = (s) => document.querySelector(s);
const esc = (s) => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const chevron = (direction) => `<svg class="chevron ${direction}" viewBox="0 0 12 12" fill="none" aria-hidden="true"><path d="M3.3 4.65 6 7.35 8.7 4.65" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const check = '<svg class="check-icon" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="m3 8 3 3 7-7" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const badge = (value) => `<span class="wire-badge"><span class="wire-badge-label">${esc(value)}</span></span>`;
const button = (text, action, disabled = false, primary = false) => `<button type="button" class="wire-button" data-variant="${primary ? 'primary' : 'neutral'}" data-action="${action}" ${disabled ? 'disabled' : ''}>${primary ? check : ''}${text}</button>`;
const rows = (values) => `<dl class="wire-data-rows">${values.map(([label,value]) => `<div class="wire-data-row"><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl>`;
const section = (title, body) => `<section class="wire-card-section"><h3>${esc(title)}</h3>${body}</section>`;
const roles = ['all','admin','tech','lead','counselor','both'];
const params = new URLSearchParams(location.search);
const state = {variant:params.get('variant') === 'B' ? 'B' : 'A',role:roles.includes(params.get('role')) ? params.get('role') : 'all',detail:null,open:new Set(),values:{institution:'햇살연대',timezone:'Asia/Seoul',retention:'1',export:'가명 통계',team:'자립지원팀'},ai:{step:0,path:'off',checked:false,confirmed:false,applied:'off'},notes:{}};
let businessReconfirmationRequired = false;
const modules = [
{id:'institution',title:'기관 기본',group:'기관과 사람',purpose:'기관 이름과 업무 기준을 한곳에서 관리합니다.',owner:'기관 관리자',status:'예시: 기본 정보 등록',roles:['admin','both'],rows:[['기관 이름','햇살연대'],['업무 시간대','Asia/Seoul'],['기관 구성','실무자 12명 / 팀 3개'],['진행 규모','케이스 48개 / 사업 3개']]},
{id:'people',title:'사용자와 역할',group:'기관과 사람',purpose:'업무 역할, 팀 감독과 담당 배정을 구분합니다.',owner:'기관 관리자',status:'예시: 사용자 12명',roles:['admin','both'],rows:[['팀 구성','자립지원팀 5명 / 생활회복팀 4명 / 지역협력팀 3명'],['감독 담당','각 팀에 실무 책임자 1명'],['배정 요청','공동 담당 요청 2건'],['기관 기술 관리자','연결 준비와 계정 보안 담당. 상담 내용 접근 없음']]},
{id:'programs',title:'사업 관리',group:'기관과 사람',purpose:'사업별 저장 위치와 처리 경로의 도입 확인을 관리합니다.',owner:'기관 관리자',status:'예시: 1개 사업 확인 전',roles:['admin','both'],rows:[['청년 자립','확인 완료 / Supabase 서울 / 외부 허용'],['생활 회복','도입 확인 전 / 저장 위치 나중에 정하기 / 기관 안'],['2025 재도약','종료 / Supabase 서울 / 외부 허용'],['변경 시 확인','설치 AI 설정이 바뀌면 진행 사업 2개 재확인']]},
{id:'ai',title:'AI와 STT',group:'연결과 저장',purpose:'연결 준비와 최종 시작을 나누고, 나가는 자료를 확인합니다.',owner:'기관 관리자: 키와 최종 시작 / 기술 관리자: 연결 준비',status:'예시: AI 꺼짐',roles:['admin','tech','both'],rows:[['설치 LLM','off / OpenAI 연결 준비 예시, 실제 연결 없음'],['설치 STT','off / 엔진 null'],['로컬 STT','STT-G1~G3 실측 및 Q 승인 전 선택 불가'],['키 관리','기관 관리자가 입력하고 최종 시작을 결정'],['기술 관리자','연결 준비만 수행. 최종 시작과 키 변경은 불가']]},
{id:'database',title:'데이터베이스',group:'연결과 저장',purpose:'저장 위치와 설치 점검 범위를 확인합니다.',owner:'기관 기술 관리자',status:'예시: 서울 저장소',roles:['tech','both'],rows:[['배포 형태','Community Cloud'],['저장 위치','기관 소유 Supabase / 서울'],['사전 점검','변경 없는 plan부터 시작'],['이전 조건','백업, 접근 범위, 복구 계획을 별도로 검토']]},
{id:'files',title:'파일과 내보내기',group:'연결과 저장',purpose:'파일 사용량, 백업과 내보내기 이력을 살펴봅니다.',owner:'기관 관리자: 내보내기 / 기술 관리자: 백업과 복구',status:'예시: 2.4 GB 사용',roles:['admin','tech','both'],rows:[['파일 사용량','2.4 GB / 20 GB'],['최근 백업','9월 8일 02:00 완료 (예시 이력)'],['이전 백업','9월 7일 02:00 실패 / 저장 대상 확인 필요'],['복구와 이전','검증된 백업과 별도 실행 확인 필요. 이 시안에서는 실행하지 않음']]},
{id:'memory',title:'메모리 관리',group:'기록 운영',purpose:'누적 맥락의 처리 현황만 봅니다. 내용은 상담 화면에서 확인합니다.',owner:'기관 관리자',status:'예시: 요약 126개',roles:['admin','both'],rows:[['요약 현황','케이스 48개 / 누적 요약 126개'],['처리 대기','마스킹 대기 4개 / 검토 필요 2개'],['재료 원칙','공식 기록과 장비가 가린 스냅샷만 사용'],['내용 열람','설정에서 요약 원문, 당사자 이름, 인용을 표시하지 않음']]},
{id:'consent',title:'동의와 보존',group:'기록 운영',purpose:'동의 영역과 종결 후 보존 기준을 확인합니다.',owner:'기관 관리자',status:'예시: 기본 보존 1년',roles:['admin','both'],rows:[['동의 영역','개인정보, 녹음, 외부 STT, 텍스트 AI 등 6영역'],['미동의 경로','수기 기록 이용. 기존 동의를 새 영역으로 자동 승격하지 않음'],['보존 시작','마지막 활성 케이스 종결 시'],['기간 도래','먼저 아카이브로 옮긴 뒤 관리자가 보존 또는 파기 검토'],['비법적 보존 상한','종결 후 총 5년']]},
{id:'security',title:'보안과 감사',group:'기록 운영',purpose:'계정 보안과 업무 열람 감사의 범위를 나눠 확인합니다.',owner:'기관 관리자: 업무 감사 / 기술 관리자: 계정 보안',status:'예시: 관리자 MFA 사용',roles:['admin','tech','both'],rows:[['계정 보안','관리자 계정 MFA 사용 예시'],['업무 역할','기관 관리자, 실무 책임자, 실무자 역할은 별도 관리'],['감사 원칙','열람, 변경, 개인정보 복호화, 내보내기 기록'],['지원 접근','마스킹된 자료만 허용']]},
{id:'devices',title:'처리 장비와 업데이트',group:'연결과 저장',purpose:'장비 연결과 업데이트 준비 상태를 확인합니다.',owner:'기관 기술 관리자',status:'예시: 장비 1대 연결 끊김',roles:['tech','both'],rows:[['처리 장비 A','연결 정상 예시 / 마지막 확인 5분 전'],['처리 장비 B','연결 끊김 예시 / 마지막 확인 7시간 전'],['일감 처리','녹음 0개 / 텍스트 마스킹 4개 대기'],['업데이트','서명 확인, 백업 후 적용과 되돌리기 필요']]}
];
const account = {id:'account',title:'내 계정과 접근 범위',group:'내 업무',purpose:'내 계정 보안과 담당 또는 감독 범위를 확인합니다.',owner:'본인: 계정 / 기관 관리자: 업무 역할',status:'예시: 계정 사용 중',roles:roles,rows:[]};
const isAdmin = () => ['all','admin','both'].includes(state.role);
const isTech = () => ['all','tech','both'].includes(state.role);
const visible = () => [...modules.filter(m => state.role==='all'||m.roles.includes(state.role)),account];
const moduleById = id => [...modules,account].find(m=>m.id===id);
function moduleRows(m){
 if(m.id==='account') return [['프리뷰 계정','시연 사용자'],['로그인과 MFA','계정 보안 예시 / 실제 변경 없음'],['업무 범위',state.role==='lead'?'지정된 자립지원팀 감독, 읽기 전용':state.role==='counselor'?'담당 배정된 케이스의 상담 기록':state.role==='tech'?'연결 준비와 계정 보안. 당사자 신원과 상담 내용 접근 없음':'선택한 역할에 맞는 업무 범위'],['역할 변경','기관 관리자에게 요청. 계정 MFA 변경과는 별개']];
 if(m.id==='security'&&state.role==='tech') return [['계정 MFA','관리자 계정 3개 설정 예시'],['로그인 점검','최근 계정 보안 점검 9월 8일'],['업무 감사','기관 관리자 전용. 이 보기에는 표시하지 않음'],['권한 구분','로그인 계정 관리로 업무 열람 권한이 생기지 않음']];
 return m.rows.map(row=>m.id==='institution'&&row[0]==='기관 이름'?[row[0],state.values.institution]:m.id==='consent'&&row[0]==='보존 시작'?row:row);
}
const input = (key,label,value,type='text') => `<label class="field"><span class="wire-form-label">${label}</span><input type="${type}" data-value="${key}" value="${esc(value)}" ${type==='number'?'min="1" max="5"':''}></label>`;
function impact(title,body){return `<aside class="impact" aria-label="변경 영향 예시"><h3>변경 영향 예시</h3><div class="impact-section"><p class="label">${esc(title)}</p><p class="value">${esc(body)}</p></div><div class="impact-section"><p class="label">실제 적용</p><p class="value">이 화면 안에서만 바뀝니다. 저장, 연결, 외부 전송은 하지 않습니다.</p></div></aside>`;}
function aiImpact(){let path=state.ai.path;return `<aside class="impact" aria-label="AI 변경 영향 예시"><h3>변경 영향 예시</h3>${[['설치 설정',path==='off'?'LLM off / STT off':path==='openai'?'LLM openai / STT off':'LLM off / STT azure'],['사업별 상한','청년 자립: 외부 허용. 생활 회복: 기관 안. 실효 기능은 설치 설정과 사업별 허용 범위 중 더 좁은 쪽입니다.'],['밖으로 나가는 자료',path==='openai'?'OpenAI: 장비가 가린 텍스트만 전송하는 경로입니다. 원음은 보내지 않습니다.':path==='azure'?'Azure STT: 마스킹 전 원음이 외부로 나갑니다. 녹음과 외부 STT 동의를 별도로 확인해야 합니다.':'외부 AI 호출 없음. 수기 기록은 계속 사용할 수 있습니다.'],['사업 재확인',state.ai.applied===path&&!businessReconfirmationRequired?'시연 설정을 아직 변경하지 않았습니다. 생활 회복은 기존 도입 확인도 필요합니다.':'2개 사업 재확인 필요. 설정 적용만으로 사업 확인이 끝나지는 않습니다.'],['로컬 STT','엔진 null. STT-G1~G3와 Q 승인 전에는 사용할 수 없습니다.']].map(([a,b])=>`<div class="impact-section"><p class="label">${a}</p><p class="value">${b}</p></div>`).join('')}</aside>`;}
function aiForm(){const a=state.ai;let field='';if(a.step===0) field=`<label class="field"><span class="wire-form-label">어떤 처리 경로를 검토할까요?</span><select id="ai-path"><option value="off" ${a.path==='off'?'selected':''}>AI 사용 안 함</option><option value="openai" ${a.path==='openai'?'selected':''}>OpenAI 텍스트 AI</option><option value="azure" disabled>Azure 음성 전사 (승인 대기)</option><option disabled>기관 안 로컬 STT (Q 승인 대기)</option></select></label><p class="meta">연결 준비는 기술 관리자가, API 키 관리와 최종 시작은 기관 관리자가 맡습니다. 실제 키는 입력하지 않습니다.</p><p class="meta">Azure는 마스킹 전 원음을 외부로 보내므로 녹음과 외부 STT 동의가 필요합니다. 현재는 켤 수 없습니다.</p>`;
 if(a.step===1) field=`<div class="field"><p class="wire-form-label">연결 확인 절차를 시연할까요?</p><p class="value">${a.checked?'시연 점검표를 확인했습니다. 실제 연결 상태는 알 수 없습니다.':'연결 대상, 동의와 건강한 처리 장비를 확인하는 순서만 보여 줍니다.'}</p>${button('연결 확인 시연','ai-check',!isAdmin()&&!isTech())}<p class="meta">네트워크 요청을 보내지 않습니다. 외부 연결 성공을 뜻하지 않습니다.</p></div>`;
 if(a.step===2) field=`<label class="choice"><input id="ai-confirm" type="checkbox" ${a.confirmed?'checked':''} ${!isAdmin()?'disabled':''}>변경 영향과 사업 재확인 안내를 읽었나요?</label><p class="meta">${isAdmin()?'기관 관리자 역할로 시연 적용할 수 있습니다. 실제 AI는 시작하지 않습니다.':'기관 관리자가 최종 시작을 결정합니다. 기술 관리자 역할은 연결 준비까지만 가능합니다.'}</p>`;
 return `<ol class="steps">${['처리 경로','연결 확인 시연','변경 내용 확인'].map((s,i)=>`<li ${i===a.step?'aria-current="step"':''}>${i+1}. ${s}</li>`).join('')}</ol><div class="detail-grid"><div class="detail-fields">${field}<div class="actions">${button('이전','ai-prev',a.step===0)}${a.step<2?button('다음','ai-next',a.step===1&&!a.checked):button('시연 적용','ai-apply',!a.confirmed||!isAdmin(),true)}${button('처음부터','ai-reset')}</div></div>${aiImpact()}</div>`;
}
function controls(m){
 let form='', explanation='', title='영향 범위';
 switch(m.id){
 case 'institution':form=input('institution','화면에 표시할 기관 이름',state.values.institution)+button('시연 적용','save-institution',!isAdmin(),true);explanation='설정 목록과 기관 표시 이름을 바꿔 보는 시연입니다.';break;
 case 'people':form=`<label class="field"><span class="wire-form-label">배정 요청을 검토할 팀</span><select data-value="team">${['자립지원팀','생활회복팀','지역협력팀'].map(t=>`<option ${t===state.values.team?'selected':''}>${t}</option>`).join('')}</select></label>${button('배정 검토 시연','save-people',!isAdmin(),true)}`;explanation='계정 로그인 권한이 아니라 담당과 감독 관계를 검토합니다. 실제 배정은 바뀌지 않습니다.';break;
 case 'programs':form=section('사업별 예시 상태',`<p class="value">청년 자립 ${badge('확인 완료')}</p><p class="value">생활 회복 ${badge('도입 확인 전')}</p><p class="value">2025 재도약 ${badge('종료')}</p>`)+button('AI 설정 영향 보기','goto-ai');explanation='도입 확인 전인 사업은 실제 데이터 등록과 AI 시작의 전제 조건을 충족하지 않은 예시입니다.';break;
 case 'database':form=`<p class="value">저장소 이전은 여기서 즉시 실행하지 않습니다.</p>${button('사전 점검 범위 보기','plan-database')}${button('실제 데이터베이스 이전', 'none',true)}`;explanation='읽기 전용 plan, 백업과 복구 검토가 먼저입니다. 주소나 연결 문자열은 입력하지 않습니다.';break;
 case 'files':form=(isAdmin()?`${section('내보내기 이력 예시',rows([['9월 6일','가명 통계 / 완료'],['9월 3일','사업 집계 / 완료']]))}<label class="field"><span class="wire-form-label">내보내기 범위 예시</span><select data-value="export">${['가명 통계','사업 집계'].map(value=>`<option ${state.values.export===value?'selected':''}>${value}</option>`).join('')}</select></label>${button('범위 선택 시연','save-files',false,true)}`:'<p class="value">기술 관리자 보기에는 파일 내용과 업무 내보내기 이력을 표시하지 않습니다.</p>')+(isTech()?button('백업 점검 순서 보기','plan-files'):'');explanation='선택한 범위만 화면에 표시합니다. 다운로드나 백업, 복구, 모드 이전을 수행하지 않습니다.';break;
 case 'memory':form=`<p class="value">누적 맥락 126개는 처리 건수 예시입니다. 메모리 원문은 이 설정 화면에 없습니다.</p>${button('마스킹 처리 경로 보기','goto-ai')}`;explanation='요약과 근거의 실제 내용은 담당 권한이 있는 상담 화면에서만 확인합니다.';break;
 case 'consent':form=input('retention','기본 보존 기간 (년)',state.values.retention,'number')+button('보존 기준 시연 적용','save-consent',!isAdmin(),true);explanation='1~5년 범위에서 예시 기준만 바꿉니다. 동의 갱신, 실제 보존 기한과 파기에는 영향을 주지 않습니다.';break;
 case 'security':form=`<p class="value">${state.role==='tech'?'계정과 MFA 점검만 보여 줍니다. 업무 감사 원문과 당사자 정보는 숨깁니다.':'기관 설정 변경 3건, 가명 통계 내보내기 2건의 감사 집계 예시입니다.'}</p>${button('내 계정과 접근 범위 보기','goto-account')}`;explanation='계정 보안 설정이 업무 역할이나 상담 내용 접근 권한을 부여하지 않습니다.';break;
 case 'devices':form=`<p class="value">연결 끊김 장비는 새 일감을 받지 못하는 예시입니다.</p>${button('업데이트 확인 순서 보기','plan-devices')}${button('실제 업데이트 설치','none',true)}`;explanation='전원과 통신 확인 후 서명, 백업과 되돌리기 준비를 확인합니다. 실제 장비에 명령을 보내지 않습니다.';break;
 case 'account':form=`<p class="value">${state.role==='lead'?'자립지원팀의 담당 기록을 읽기 전용으로 감독하는 예시입니다.':state.role==='counselor'?'배정된 케이스만 작성할 수 있는 실무자 보기입니다.':'로그인 계정과 업무 역할은 별개입니다.'}</p>${button('계정 보안 안내 보기','plan-account')}${button('실제 MFA 변경','none',true)}`;explanation='권한 변경은 기관 관리자에게 요청합니다. 이 화면의 역할 선택은 실제 권한을 바꾸지 않습니다.';break;
 }
 return `<div class="detail-grid"><div class="detail-fields">${form}<p class="meta" data-feedback="${m.id}" role="status">${esc(state.notes[m.id]||'')}</p></div>${impact(title,explanation)}</div>`;
}
function body(m){return section('현재 설정 예시',rows(moduleRows(m)))+section(m.id==='ai'?'AI 설정 3단계 시연':'설정 살펴보기',m.id==='ai'?aiForm():controls(m));}
function summary(m){return `<div class="module-title-stack"><div class="summary-title"><span class="wire-card-title">${esc(m.title)}</span>${badge(m.id==='ai'&&state.ai.applied!=='off'?'예시: 시연 적용됨':m.status)}</div><p class="meta">${esc(m.purpose)}</p><div class="module-owner"><span class="label">담당</span><span class="value">${esc(m.owner)}</span></div><p class="meta">연결 전 시안</p></div>`;}
function cardA(m){return `<a class="surface-card wire-card module-link" href="?variant=A&role=${state.role}&module=${m.id}" data-module="${m.id}">${summary(m)}<div class="module-footer"><span class="meta">설정 보기</span>${chevron('right')}</div></a>`;}
function cardB(m){return `<details class="surface-card wire-card wire-card-details" id="module-${m.id}" data-module-id="${m.id}" ${state.open.has(m.id)?'open':''}><summary class="wire-card-summary">${summary(m)}<span class="wire-chevron-button">${chevron('down')}</span></summary><div class="wire-card-body">${body(m)}</div></details>`;}
function syncURL(){const url=new URL(location.href);url.searchParams.set('variant',state.variant);url.searchParams.set('role',state.role);url.searchParams.delete('module');if(state.detail&&state.variant==='A')url.searchParams.set('module',state.detail);history.replaceState(null,'',url);}
function render(){const list=visible();if(state.detail&&!list.some(m=>m.id===state.detail))state.detail=null;$('#role').value=state.role;$('#variant-label').textContent=state.variant==='A'?'A / 전체에서 상세로':'B / 한 화면에서 펼치기';$('#role-note').textContent=['counselor','lead'].includes(state.role)?'기관 운영 설정은 숨겼습니다. 내 계정과 담당 또는 감독 범위만 살펴봅니다. 실제 권한 검사가 아닌 시안입니다.':state.role==='tech'?'연결 준비와 계정 보안만 봅니다. 당사자 신원, 상담 내용과 업무 역할 관리 화면은 표시하지 않습니다.':'역할별 화면을 비교하는 기능입니다. 실제 권한 검사나 계정 변경은 하지 않습니다.';
 if(state.variant==='A'&&state.detail){const m=moduleById(state.detail);$('#content').innerHTML=`<div class="back-row">${button(chevron('left')+'전체 설정','back')}</div><section class="surface-card wire-card"><div class="detail-intro">${summary(m)}</div><hr class="wire-card-divider"><div class="wire-card-body">${body(m)}</div></section>`;}
 else $('#content').innerHTML=`<p class="meta">${state.variant==='A'?'설정 카드를 누르면 상세 화면으로 이동합니다.':'설정 항목을 펼쳐 같은 화면에서 비교합니다. 여러 항목을 함께 열 수 있습니다.'} ${list.length}개 항목 표시</p>`+['기관과 사람','연결과 저장','기록 운영','내 업무'].map(group=>{const entries=list.filter(m=>m.group===group);return entries.length?`<section class="group"><h2>${group}</h2><div class="${state.variant==='A'?'module-grid':'module-list'}">${entries.map(state.variant==='A'?cardA:cardB).join('')}</div></section>`:'';}).join('');
 document.querySelectorAll('details[data-module-id]').forEach(el=>el.addEventListener('toggle',()=>{if(el.isConnected)el.open?state.open.add(el.dataset.moduleId):state.open.delete(el.dataset.moduleId);}));
 syncURL();
}
function announce(text){$('#announcement').textContent=text;}
function captureOpenModules(){document.querySelectorAll('details[data-module-id]').forEach(el=>el.open?state.open.add(el.dataset.moduleId):state.open.delete(el.dataset.moduleId));}
function focusHeading(el){if(el){el.tabIndex=-1;el.focus();}}
function go(id){if(!visible().some(m=>m.id===id))return;if(state.variant==='A')state.detail=id;else state.open.add(id);render();if(state.variant==='B')$(`#module-${id}>summary`).focus();else focusHeading($('.detail-intro .wire-card-title'));}
function switchVariant(){captureOpenModules();state.variant=state.variant==='A'?'B':'A';if(state.detail)state.open.add(state.detail);render();announce(`${state.variant} 시안으로 바꿨습니다. 선택한 역할과 시연 값은 유지됩니다.`);}
$('#previous').innerHTML=chevron('left');$('#next').innerHTML=chevron('right');$('#previous').onclick=switchVariant;$('#next').onclick=switchVariant;$('#nav-settings').onclick=()=>{state.detail=null;render();window.scrollTo(0,0);};
$('#role').onchange=e=>{state.role=e.target.value;state.detail=null;state.open.clear();state.ai.confirmed=false;render();announce('프리뷰 역할을 바꿨습니다. 실제 계정과 권한은 바뀌지 않았습니다.');};
$('#content').addEventListener('input',e=>{if(e.target.dataset.value)state.values[e.target.dataset.value]=e.target.value;});
$('#content').addEventListener('change',e=>{captureOpenModules();if(e.target.dataset.value)state.values[e.target.dataset.value]=e.target.value;if(e.target.id==='ai-path'){state.ai.path=e.target.value;state.ai.checked=false;state.ai.confirmed=false;render();$('#ai-path')?.focus();}if(e.target.id==='ai-confirm'){state.ai.confirmed=e.target.checked;const apply=$('[data-action="ai-apply"]');if(apply)apply.disabled=!state.ai.confirmed||!isAdmin();}});
$('#content').addEventListener('click',e=>{captureOpenModules();const link=e.target.closest('[data-module]');if(link){e.preventDefault();go(link.dataset.module);return;}const target=e.target.closest('[data-action]');if(!target||target.disabled)return;const action=target.dataset.action;
 if(action==='back'){const previous=state.detail;state.detail=null;render();$(`[data-module="${previous}"]`)?.focus();return;}if(action.startsWith('goto-')){go(action.slice(5));return;}
 if(action==='ai-prev')state.ai.step=Math.max(0,state.ai.step-1);
 if(action==='ai-next')state.ai.step=Math.min(2,state.ai.step+1);
 if(action==='ai-check')state.ai.checked=true;
 if(action==='ai-reset')state.ai={step:0,path:'off',checked:false,confirmed:false,applied:state.ai.applied};
 if(action==='ai-apply'&&isAdmin()&&state.ai.confirmed){businessReconfirmationRequired ||= state.ai.applied!==state.ai.path;state.ai.applied=state.ai.path;announce('시연 적용했습니다. 실제 저장이나 AI 시작은 하지 않았습니다. 사업별 재확인은 별도입니다.');}
 if(action.startsWith('save-')){const id=action.slice(5);if(id==='consent'&&(!/^[1-5]$/.test(state.values.retention))){announce('보존 기간은 1~5년으로 입력해 주세요.');return;}if(id==='institution'&&!state.values.institution.trim()){announce('기관 이름을 입력해 주세요.');return;}state.notes[id]=`시연 적용: ${id==='institution'?state.values.institution:id==='consent'?state.values.retention+'년':id==='people'?state.values.team:state.values.export}. 실제 저장하지 않았습니다.`;announce(state.notes[id]);}
 if(action.startsWith('plan-')){const id=action.slice(5);state.notes[id]=({database:'사전 점검: 리전과 읽기 권한, 기존 자료, 설치 버전, RLS, Auth, Storage를 변경 없이 확인합니다.',files:'백업 점검: 대상 위치와 용량, 암호화, 마지막 백업 결과, 복원 검증 여부를 확인합니다.',devices:'업데이트 순서: 장비 연결 확인, 서명 확인, 백업, 적용, 장애 시 되돌리기입니다.',account:'계정 보안: 본인의 로그인 수단과 MFA를 확인합니다. 업무 역할과 담당 변경은 기관 관리자에게 요청합니다.'})[id];}
 render();
 if(action.startsWith('ai-'))focusHeading($('.steps [aria-current="step"]'));
 else if(action.startsWith('save-')||action.startsWith('plan-'))focusHeading($(`[data-feedback="${action.split('-')[1]}"]`));
});
document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||e.shiftKey||e.target.closest('input,textarea,select,[contenteditable]:not([contenteditable="false"])'))return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();switchVariant();}});
if(params.get('module')&&visible().some(m=>m.id===params.get('module')))state.detail=params.get('module');
render();
